global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "chatbox-identity"
    static_configs:
      - targets: ["identity:3001"]
    metrics_path: /metrics
    scrape_interval: 10s

  - job_name: "chatbox-chat"
    static_configs:
      - targets: ["chat:3002"]
    metrics_path: /metrics
    scrape_interval: 10s

  - job_name: "chatbox-persister"
    static_configs:
      - targets: ["persister:3003"]
    metrics_path: /metrics
    scrape_interval: 10s

  - job_name: "traefik"
    static_configs:
      - targets: ["traefik:8080"]
    metrics_path: /metrics
    scrape_interval: 15s

  - job_name: "pgbouncer"
    static_configs:
      - targets: ["pgbouncer-exporter:9127"]
    metrics_path: /metrics
    scrape_interval: 15s

  - job_name: "redis"
    static_configs:
      - targets: ["redis-exporter:9121"]
    metrics_path: /metrics
    scrape_interval: 15s

  - job_name: "node"
    static_configs:
      - targets: ["node-exporter:9100"]
    metrics_path: /metrics
    scrape_interval: 15s
